/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import model.CauHoi;
import model.DeThi;
import model.QLMH;

/**
 *
 * @author ADMIN
 */
public class ChonDeThi extends javax.swing.JFrame {
    protected ChonMonHoc chonMonHoc;
    private ArrayList<DeThi> dsDeThi = new ArrayList<DeThi>();  //mảng đề thi tạm thời để thêm, sửa, xóa đề thi cho môn học  
    private int cm; //cm = 0 là đang tạo đề thi mới, cm = 1 là đang sửa đề thi

    /**
     * Creates new form ChonDeThi
     */
    public ChonDeThi() {
        initComponents();
    }
    
    
    public ChonDeThi(ChonMonHoc chonMonHoc, ArrayList<DeThi> dsDeThi) {
        initComponents();
        btnSuaDeThi.setEnabled(false);      //nút sửa đề thi không bấm đc khi chưa chọn 1 đề thi nào đó trên bảng
        this.chonMonHoc = chonMonHoc;   
        for (DeThi deThi : dsDeThi){
            this.dsDeThi.add(deThi);        //đưa danh sách các đề thi của môn học đc chọn vào
        loadDsDeThi(this.dsDeThi);
        }
    }
        
    public void loadDsDeThi(ArrayList<DeThi> dsDeThi){      //hàm hiển thị các đề thi của môn học lên bảng
        DefaultTableModel tblModel = (DefaultTableModel) tblDeThi.getModel();
        while (tblDeThi.getRowCount() != 0){
            tblModel.removeRow(0);
        }
        for (DeThi deThi : dsDeThi){
            String data[] = {deThi.getTenDeThi() + " kỳ " + deThi.getKyHoc() + " năm học " + deThi.getNamHoc()};
            tblModel.addRow(data);
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnSuaDeThi = new javax.swing.JButton();
        btnTaoDeThiMoi = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDeThi = new javax.swing.JTable();
        btnOK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnSuaDeThi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSuaDeThi.setText("Sửa đề thi");
        btnSuaDeThi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaDeThiActionPerformed(evt);
            }
        });

        btnTaoDeThiMoi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnTaoDeThiMoi.setText("Tạo đề thi mới");
        btnTaoDeThiMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaoDeThiMoiActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Quản lý đề thi");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Mở đề thi có sẵn");

        tblDeThi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Danh sách đề thi"
            }
        ));
        tblDeThi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDeThiMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblDeThi);

        btnOK.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(btnSuaDeThi)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnOK))
                        .addComponent(jLabel1)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(357, 357, 357)
                            .addComponent(btnTaoDeThiMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btnTaoDeThiMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSuaDeThi)
                    .addComponent(btnOK))
                .addGap(182, 182, 182))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTaoDeThiMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaoDeThiMoiActionPerformed
        // nút tạo đề thi mới
            this.setVisible(false);
            ChonCachTaoDeThi chonCachTaoDeThi = new ChonCachTaoDeThi(this);
            chonCachTaoDeThi.setVisible(true);
            chonCachTaoDeThi.pack();
            chonCachTaoDeThi.setLocationRelativeTo(null);
            chonCachTaoDeThi.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_btnTaoDeThiMoiActionPerformed

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        // nút quay lại giao diện trước
        this.setVisible(false);
        this.chonMonHoc.setVisible(true);
    }//GEN-LAST:event_btnOKActionPerformed

    private void tblDeThiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDeThiMouseClicked
        // khi click vào 1 đề thi nào đó trong bảng 
        btnSuaDeThi.setEnabled(true);   //thì nút sửa đề thi có thể bấm được để sửa đề đã chọn
        
        
    }//GEN-LAST:event_tblDeThiMouseClicked

    private void btnSuaDeThiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaDeThiActionPerformed
        // nút sửa đề thi có sẵn
        this.setVisible(false);
        TaoDeThi taoDeThi = new TaoDeThi(this,QLMH.getMonHoc(this.chonMonHoc.getCbbDsMonHoc().getSelectedIndex()).getDsCauHoi(),QLMH.getMonHoc(this.chonMonHoc.getCbbDsMonHoc().getSelectedIndex()).getDsDeThi().get(this.tblDeThi.getSelectedRow()));
        taoDeThi.setVisible(true);
            taoDeThi.pack();
            taoDeThi.setLocationRelativeTo(null);
            taoDeThi.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_btnSuaDeThiActionPerformed

    public JTable getTblDeThi() {
        return tblDeThi;
    }

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChonDeThi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChonDeThi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChonDeThi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChonDeThi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChonDeThi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOK;
    private javax.swing.JButton btnSuaDeThi;
    private javax.swing.JButton btnTaoDeThiMoi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblDeThi;
    // End of variables declaration//GEN-END:variables
}
