/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import model.BaiLam;
import model.CauTraLoi;
import model.CauTraLoiTL;
import model.DeThi;
import model.MonHoc;
import model.QLBL;
import model.QLMH;

/**
 *
 * @author ADMIN
 */
public class DanhSanhBailam extends javax.swing.JFrame {
    private ChonMonHoc chonMonHoc;
    private BaiLam baiLam;
    private DanhSachDeThiChamDiem dsDeThi;
    private ArrayList<BaiLam> dsBaiLam = new ArrayList<>();

    public DanhSanhBailam() {
        initComponents();        
    }
    
    public DanhSanhBailam(DanhSachDeThiChamDiem dsDeThi, ArrayList<BaiLam> dsBaiLam){
        initComponents();
        this.dsDeThi = dsDeThi;
        btnChamDiem.setEnabled(false);     
        for (BaiLam baiLam : dsBaiLam){
            this.dsBaiLam.add(baiLam);      
        }
        loadDsBaiLam();
        
    }    
    
    public void loadDsBaiLam(){     //hàm hiển thị các bài làm lên bảng
        DefaultTableModel tblModel = (DefaultTableModel) tblBaiLam.getModel();
        while (tblBaiLam.getRowCount() != 0){
            tblModel.removeRow(0);
        }
        for (BaiLam bl : this.dsBaiLam){
            Object data[] = {
                bl.getUser().getTenDangNhap(),
                bl.getDiemTN(),
                bl.getDiemTL()==-1?"Chưa chấm":bl.getDiemTL(),
                bl.getDiemTL()==-1?bl.getDiemTN():bl.getDiemTN()+bl.getDiemTL()
                
            };
            tblModel.addRow(data);                
        }
    }
    
    public void capNhatBaiLam(int index, BaiLam baiLam){        //hàm cập nhật lại điểm số của bài làm
        this.dsBaiLam.remove(index);                //xóa bài làm cũ
        this.dsBaiLam.add(index, baiLam);           //thay bằng bài làm mới tương tự nhưng đã có điểm tự luận
    }
    
    public ArrayList<BaiLam> getDsBaiLam() {
        return dsBaiLam;
    }

    public JTable getTblBaiLam() {
        return tblBaiLam;
    }
    
    public void xoaTableBaiLam(){                   //hàm xóa bảng
        DefaultTableModel tblModel = (DefaultTableModel) tblBaiLam.getModel();
        while (tblBaiLam.getRowCount() != 0){
            tblModel.removeRow(0);
        }
    }
    
   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblBaiLam = new javax.swing.JTable();
        btnChamDiem = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("DANH SÁCH BÀI LÀM");

        tblBaiLam.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User", "Điểm TN", "Điểm TL", "Tổng"
            }
        ));
        tblBaiLam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBaiLamMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblBaiLam);

        btnChamDiem.setText("Chấm Điểm Tự Luận");
        btnChamDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChamDiemActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(btnChamDiem, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnChamDiem)
                    .addComponent(btnCancel))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblBaiLamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBaiLamMouseClicked
        // TODO add your handling code here:
        btnChamDiem.setEnabled(true);
        this.baiLam = this.dsBaiLam.get(this.tblBaiLam.getSelectedRow());
    }//GEN-LAST:event_tblBaiLamMouseClicked

    private void btnChamDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChamDiemActionPerformed
        // mở giao diện chấm điểm tự luận cho bài làm
        if (this.baiLam.getDsCauTraLoi().size() == 0){
            JOptionPane.showMessageDialog(null, "Đề thi không có phần tự luận");
        } else { 
                    this.setVisible(false);
            ChamBaithiTL lamBaiThi = new ChamBaithiTL(this.baiLam,this);
            lamBaiThi.setVisible(true);
            lamBaiThi.pack();
            lamBaiThi.setLocationRelativeTo(null);
            lamBaiThi.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        }
            
    }//GEN-LAST:event_btnChamDiemActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        xoaTableBaiLam();
        while (!this.dsDeThi.getDsBaiLam().isEmpty()){
            this.dsDeThi.getDsBaiLam().remove(0);
        }
        this.setVisible(false);
        this.dsDeThi.setVisible(true);
    }//GEN-LAST:event_btnCancelActionPerformed

   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DanhSanhBailam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DanhSanhBailam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DanhSanhBailam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DanhSanhBailam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DanhSanhBailam().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnChamDiem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblBaiLam;
    // End of variables declaration//GEN-END:variables
}
