/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import model.BaiLam;
import model.DeThi;
import model.QLBL;
import model.QLMH;

/**
 *
 * @author ADMIN
 */


public class DanhSachDeThiChamDiem extends javax.swing.JFrame {
    private ChonMonHoc chonMonHoc;
    private DeThi deThi;        //biến đề thi tạm thời dùng để lưu lựa chọn đề thi của người dùng
    private ArrayList<DeThi> dsDeThi = new ArrayList<>();
    private ArrayList<BaiLam> dsBaiLam = new ArrayList<>();

    
    public DanhSachDeThiChamDiem() {
        initComponents();
    }
    
    public DanhSachDeThiChamDiem(ChonMonHoc chonMonHoc, ArrayList<DeThi> dsDeThi){
        initComponents();
        btnDsBaiLam.setEnabled(false);
        this.chonMonHoc = chonMonHoc;
        for (DeThi deThi : dsDeThi){
            this.dsDeThi.add(deThi);
        loadDsDeThi(this.dsDeThi);
        }
    }
    
    //hàm hiển thi danh sách các đề thi của môn học đã chọn ở giao diện ChonMonHoc lên bảng
    public void loadDsDeThi(ArrayList<DeThi> dsDeThi){      
        DefaultTableModel tblModel = (DefaultTableModel) tblDeThi.getModel();
        while (tblDeThi.getRowCount() != 0){
            tblModel.removeRow(0);
        }
        for (DeThi deThi : dsDeThi){
            String data[] = {deThi.getTenDeThi() + " kỳ " + deThi.getKyHoc() + " năm học " + deThi.getNamHoc()};
            tblModel.addRow(data);
        }
    }

    public ArrayList<BaiLam> getDsBaiLam() {
        return dsBaiLam;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDeThi = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnDsBaiLam = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblDeThi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Danh sách đề thi"
            }
        ));
        tblDeThi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDeThiMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblDeThi);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("DANH SÁCH ĐỀ THI");

        btnDsBaiLam.setText("Danh sách bài làm");
        btnDsBaiLam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDsBaiLamActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addComponent(btnDsBaiLam)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancel)))
                .addContainerGap(222, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDsBaiLam)
                    .addComponent(btnCancel))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblDeThiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDeThiMouseClicked
        // khi chọn 1 đề thi nào đó thì có thể bám vào nút btnDsBaiLam để chuyển sang giao diện danh sách bài làm
        btnDsBaiLam.setEnabled(true);
        //đề thi tạm thời gán bằng đề thi đc chọn trong bảng
        this.deThi = QLMH.getMonHoc(this.chonMonHoc.getCbbDsMonHoc().getSelectedIndex()).getDsDeThi().get(this.tblDeThi.getSelectedRow());
    }//GEN-LAST:event_tblDeThiMouseClicked

    private void btnDsBaiLamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDsBaiLamActionPerformed
        // chuyển sang giao diện các danh sách bài làm của đề thi đang chọn
        for (BaiLam bl : QLBL.getDsBaiLam()){       //duyệt tất cả các phần tử của danh sách bài làm
            if (bl.getDeThi().equals(this.deThi)){      //nếu phần tử bài làm nào có thuộc tính đê thi trùng với đề thi đang chọn
                System.out.println(bl.getUser().getTenDangNhap());
                dsBaiLam.add(bl);                   //thêm vào 1 danh sách bài làm tạm thời
            }
        }
        this.setVisible(false);
        DanhSanhBailam dsBaiLam = new DanhSanhBailam(this,this.dsBaiLam);       //truyền danh sách bài làm tạm thời sang giao diện sau
        dsBaiLam.setVisible(true);
        dsBaiLam.pack();
        dsBaiLam.setLocationRelativeTo(null);
        dsBaiLam.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_btnDsBaiLamActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.chonMonHoc.setVisible(true);
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DanhSachDeThiChamDiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DanhSachDeThiChamDiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DanhSachDeThiChamDiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DanhSachDeThiChamDiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DanhSachDeThiChamDiem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDsBaiLam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblDeThi;
    // End of variables declaration//GEN-END:variables
}
