/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.MonHoc;
import model.QLMH;

/**
 *
 * @author ADMIN
 */
public class GiaoDienChinh extends javax.swing.JFrame {
    private Login login;  
    private int cm; //biến đánh dấu xem đã chọn chức năng nào. cm = 1 là soạn câu hỏi, cm = 2 là tạo đề thi
                    //cm = 3 là đánh giá kết quả
 
    

    /**
     * Creates new form GiaoDienChinh
     */
    public GiaoDienChinh() {
        initComponents();
    }
    
    public GiaoDienChinh(Login login) {
        initComponents();
        this.login = login;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnDungDeThi = new javax.swing.JButton();
        btnDanhGiaKetQua = new javax.swing.JButton();
        btnSoanCauHoi = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnDungDeThi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnDungDeThi.setText("Xây dựng đề thi");
        btnDungDeThi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDungDeThiActionPerformed(evt);
            }
        });

        btnDanhGiaKetQua.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnDanhGiaKetQua.setText("Đánh giá kết quả");
        btnDanhGiaKetQua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDanhGiaKetQuaActionPerformed(evt);
            }
        });

        btnSoanCauHoi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSoanCauHoi.setText("Soạn câu hỏi");
        btnSoanCauHoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSoanCauHoiActionPerformed(evt);
            }
        });

        btnThoat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnDanhGiaKetQua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDungDeThi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSoanCauHoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(btnSoanCauHoi, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDungDeThi, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDanhGiaKetQua, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnThoat)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDanhGiaKetQuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDanhGiaKetQuaActionPerformed
        cm = 3;             //đã chọn chức năng đánh giá kết quả

        this.setVisible(false);
        ChonMonHoc chonMonHoc = new ChonMonHoc(this);           
        chonMonHoc.setVisible(true);
        chonMonHoc.pack();
        chonMonHoc.setLocationRelativeTo(null);
        chonMonHoc.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_btnDanhGiaKetQuaActionPerformed

    private void btnSoanCauHoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSoanCauHoiActionPerformed
        cm = 1;             //đã chọn chức năng soạn câu hỏi

        this.setVisible(false);
        ChonMonHoc chonMonHoc = new ChonMonHoc(this);
        chonMonHoc.setVisible(true);
        chonMonHoc.pack();
        chonMonHoc.setLocationRelativeTo(null);
        chonMonHoc.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_btnSoanCauHoiActionPerformed

    private void btnDungDeThiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDungDeThiActionPerformed
        cm = 2;         //đã chọn chức năng tạo đề thi

        this.setVisible(false);
        ChonMonHoc chonMonHoc = new ChonMonHoc(this);
        chonMonHoc.setVisible(true);
        chonMonHoc.pack();
        chonMonHoc.setLocationRelativeTo(null);
        chonMonHoc.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_btnDungDeThiActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // nút đăng xuất
        int response = JOptionPane.showConfirmDialog(this,"Bạn có chắc chắn muốn đăng xuất không?","Xác nhận",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if (response == JOptionPane.YES_OPTION){
            this.setVisible(false);
            this.login.setVisible(true);
        }
    }//GEN-LAST:event_btnThoatActionPerformed

    public int getCm() {
        return cm;
    }

    public void setCm(int cm) {
        this.cm = cm;
    }
     
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GiaoDienChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GiaoDienChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GiaoDienChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GiaoDienChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GiaoDienChinh().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDanhGiaKetQua;
    private javax.swing.JButton btnDungDeThi;
    private javax.swing.JButton btnSoanCauHoi;
    private javax.swing.JButton btnThoat;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
